    <main class="container my-3">

        <h1>FOOTBALL</h1>

        <p>Notre association propose l'organisation de tournoi de football toute l'année !</p>
        <img src="../assets/images/football.jpg" />

        <h2>Liste des prochains Tournois de Football</h2>

        <form id="search-form">
            <div class="row">
                <div class="col">
                    <label for="search" class="visually-hidden">Rechercher</label>
                    <input type="text" class="form-control" id="search" placeholder="Taper l'évènement recherché">
                </div>
                <div class="col">
                    <button class="btn btn-primary">Rechercher</button>
                </div>
            </div>
        </form>

        <ul id="myList"></ul>
    </main>