<section class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>Bienvenue sur SportsEvent</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <p>
                Ce site a pour objectif de vous présenter les évènements sportifs autour de chez vous.
                Vous pouvez y trouver des évènements de tous types, de toutes catégories.
            </p>
        </div>
    </div>
</section>